### PR TITLE
Evolve with item

### PR DESCRIPTION
**Pull request by FernandoTBarros**
**Changes made:**

* Duplicating evolve method of Pokemon class to be able to evolve using Item
* Calling updateInventories with the response if it's a forceUpdate to fix updateInventories

### CODE REVIEW

**Comment by gegy1000** [comment]
The updateInventories change should not be necessary, the common request *should* handle the response.

**Comment by FernandoTBarros** [comment]
What common request? Should I call two updateInventories in my application? I don't see a reason why a call to updateInventories doesn't really update my inventories.

**Comment by gegy1000** [comment]
No, the API will handle the response from updateInventories because it is a common request. You don't need to add that code to handle it in the updateInventories method.

**Comment by FernandoTBarros** [comment]
Well.. it's not working unless I did this in the API code.

**Comment by RebliNk17** [comment]
Why are you forcing update for the inventory?
Anyway, restoring to the latest commit, I'm sending another one soon with a login flow fix.
Try those changes first. it should work better after i will finish my commit...

**Comment by RebliNk17** [comment]
@FernandoTBarros I am done with my commit. the login flow is accurate for now.

**Comment by FernandoTBarros** [comment]
I'm not forcing update in this commit, but just calling updateInventories without passing any argument in my app was not working. 
Everyone is complaining since the [commit ](https://github.com/FernandoTBarros/PokeGOAPI-Java/blame/84df3ebb045807f7645623268937bf3b9c9b27ff/library/src/main/java/com/pokegoapi/api/inventory/Inventories.java#L142) that changed this file.

**Comment by FernandoTBarros** [comment]
I'm closing this PR since it's not needed anymore once "evolve" method has already been done in another branch.
But my problem with updateInventories continues... I need to force update in my app because there is a REFRESH button that should give me my latest Pokemon list.

**Pull request closed without merging**
