### PR TITLE
Add the ability to use new berrys

### PR DESCRIPTION
**Pull request by RebliNk17**
Add new berrys support for CatchOption.
* option.useNanabBerry(true) // default is false
* option.usePinapBerry(true) // default is false

Initialize firstGP & firstGMO in PokemonGo#initialize
Better for the login when using PokemonGo#exit and login again.

### CODE REVIEW

**Comment by gegy1000** [comment]
I don't think we should handle that wait time, that should be handled by the API user.

**Comment by RebliNk17** [comment]
Then all this loop should be removed. 
I added this wait time only because of the loop.

**Comment by gegy1000** [comment]
Yes, but waiting is something that shouldn't be handled by the API. Leave it as it currently is. Also, if people are using it for a single throw, and have waits implemented, this will just create even longer waits and the original functionality is lost.

**Comment by RebliNk17** [comment]
https://github.com/RebliNk17/PokeGOAPI-Java/blob/e66b461649f1ed3258b24049b605a6e78fc5fd35/library/src/main/java/com/pokegoapi/api/map/pokemon/CatchablePokemon.java#L648-L649
For one catch, no wait :)

**Comment by hrk** [comment]
@RebliNk17 with all due respect, could you please perform a different pull request for each different feature? I mean: the firstGMO/firstGP commit is unrelated to the berries one, but being in the same pull request makes it harder to merge it. Hope I am not sounding rude, as I am not and I hope you understand my point.

**Comment by RebliNk17** [comment]
Avoid this PR.

**Pull request closed without merging**
