### PR TITLE
Fix stardust40

### PR DESCRIPTION
**Pull request by FernandoTBarros**
**Changes made:**

* Try/catch getStardustCostForPowerup for pokemons/players on level 40 returning 0 instead of throwing Exception

### CODE REVIEW

**Comment by gegy1000** [comment]
Why not handle this with a range check?

**Comment by FernandoTBarros** [comment]
I'm starting doing this way first, but then @RebliNk17 came with this code and I think I prefer this way, Because we will never have a problem with this exception anymore, even if Niantic raises the level someday, or anything else.

**Comment by gegy1000** [comment]
The protos return a count

**Comment by FernandoTBarros** [comment]
Ok. I will change it this way

**Pull request merged**
